<a href="https://colab.research.google.com/github/Aryan-theccool/ML/blob/main/Copy_of_Pandas_Exercise_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### How to Upload Your CSV File to Colab:

1.  **Click the 'Files' icon** on the left sidebar (looks like a folder).
2.  **Click the 'Upload to session storage' icon** (looks like an upward arrow with a cloud) or drag and drop your `Automobile_data.csv` file directly into the file browser panel.
3.  Once uploaded, the file will be accessible directly by its name in the Colab runtime (e.g., `'Automobile_data.csv'`).

After uploading, the following code will correctly reference your file.

In [114]:
# Define the path to your uploaded CSV file
CSV_FILE_PATH = 'Automobile_data.csv'

use AUTOMOBILE DATASET

Question 1: From given data set print first and last five rows

In [115]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
df.head(5)

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,0,0,0,0,0,0,0,0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,1,1,1,1,1,1,1,1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,2,2,2,2,2,2,2,2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,3,3,3,3,3,3,3,3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,4,4,4,4,4,4,4,4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [116]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
df.tail(5)

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,56,56,56,56,56,56,56,56,56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,57,57,57,57,57,57,57,57,57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,58,58,58,58,58,58,58,58,58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,59,59,59,59,59,59,59,59,59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,60,60,60,60,60,60,60,60,60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

Question 2: Clean data and update the CSV file
Replace all column values which contain ‘?’ and n.a with NaN.

In [117]:
df = pd.read_csv('/content/Automobile_data.csv', na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]})
print(df)
df.to_csv('/content/Automobile_data.csv')

    Unnamed: 0.8  Unnamed: 0.7  Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  \
0              0             0             0             0             0
1              1             1             1             1             1
2              2             2             2             2             2
3              3             3             3             3             3
4              4             4             4             4             4
..           ...           ...           ...           ...           ...
56            56            56            56            56            56
57            57            57            57            57            57
58            58            58            58            58            58
59            59            59            59            59            59
60            60            60            60            60            60

    Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  index      company  \
0              0             0             0           0      0  alfa-romero
1              1             1             1           1      1  alfa-romero
2              2             2             2           2      2  alfa-romero
3              3             3             3           3      3         audi
4              4             4             4           4      4         audi
..           ...           ...           ...         ...    ...          ...
56            56            56            56          56     81   volkswagen
57            57            57            57          57     82   volkswagen
58            58            58            58          58     86   volkswagen
59            59            59            59          59     87        volvo
60            60            60            60          60     88        volvo

     body-style  wheel-base  length engine-type num-of-cylinders  horsepower  \
0   convertible        88.6   168.8        dohc             four         111
1   convertible        88.6   168.8        dohc             four         111
2     hatchback        94.5   171.2        ohcv              six         154
3         sedan        99.8   176.6         ohc             four         102
4         sedan        99.4   176.6         ohc             five         115
..          ...         ...     ...         ...              ...         ...
56        sedan        97.3   171.7         ohc             four          85
57        sedan        97.3   171.7         ohc             four          52
58        sedan        97.3   171.7         ohc             four         100
59        sedan       104.3   188.8         ohc             four         114
60        wagon       104.3   188.8         ohc             four         114

    average-mileage    price
0                21  13495.0
1                21  16500.0
2                19  16500.0
3                24  13950.0
4                18  17450.0
..              ...      ...
56               27   7975.0
57               37   7995.0
58               26   9995.0
59               23  12940.0
60               23  13415.0

[61 rows x 19 columns]

Question 3: Find the most expensive car company name
Print most expensive car’s company name and price.

In [118]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
df = df [['company','price']][df.price==df['price'].max()]
df

          company    price
35  mercedes-benz  45400.0

In [119]:
### Question 4: Print All Toyota Cars details

In [120]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
car_Manufacturers = df.groupby('company')
toyotaDf = car_Manufacturers.get_group('toyota')
toyotaDf

,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,48,48,48,48,48,48,48,48,48,48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,49,49,49,49,49,49,49,49,49,49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,50,50,50,50,50,50,50,50,50,50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,51,51,51,51,51,51,51,51,51,51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,52,52,52,52,52,52,52,52,52,52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,53,53,53,53,53,53,53,53,53,53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,54,54,54,54,54,54,54,54,54,54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [121]:
### Question 5: Count total cars per company

In [122]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
chevrolet        3
jaguar           3
isuzu            3
honda            3
porsche          3
alfa-romero      3
dodge            2
volvo            2
Name: count, dtype: int64

In [123]:
### Question 6: Find each company's highest price car

In [124]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
car_Manufacturers = df.groupby('company')
# Use a list [[]] to select multiple columns from a GroupBy object
priceDf = car_Manufacturers[['company', 'price']].max()
priceDf

                     company    price
company
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [125]:
### Question 7: Find the average mileage of each car making company

In [126]:
import pandas as pd
df = pd.read_csv('/content/Automobile_data.csv')
car_Manufacturers = df.groupby('company')
# Use a single string or a list of strings. Since 'company' is the index, we just need 'average-mileage'
mileageDf = car_Manufacturers['average-mileage'].mean()
mileageDf

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64

In [127]:
### Question 8: Sort all cars by Price column

In [128]:
import pandas as pd
carsDf = pd.read_csv('/content/Automobile_data.csv')
carsDf = carsDf.sort_values(by=['price'], ascending=False)
display(carsDf.head(5))

,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,35,35,35,35,35,35,35,35,35,35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,11,11,11,11,11,11,11,11,11,11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,34,34,34,34,34,34,34,34,34,34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,46,46,46,46,46,46,46,46,46,46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,12,12,12,12,12,12,12,12,12,12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0

In [129]:
### Question 9: Concatenate two data frames using following conditions

In [130]:
import pandas as pd
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925, 71400]}
carsDf1 = pd.DataFrame.from_dict(GermanCars)

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500, 58900]}
carsDf2 = pd.DataFrame.from_dict(japaneseCars)

cars_concat = pd.concat([carsDf1, carsDf2], keys=["Germany", "Japan"])
display(cars_concat)

              Company   Price
Germany 0        Ford   23845
        1    Mercedes  171995
        2         BMV  135925
        3        Audi   71400
Japan   0      Toyota   29995
        1       Honda   23600
        2      Nissan   61500
        3  Mitsubishi   58900

In [131]:
### Question 10: Merge two data frames
#Create two data frames using following two Dicts, Merge two data frames, and append second data frame as a new column to first data frame.

In [132]:
import pandas as pd
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
carPriceDf = pd.DataFrame.from_dict(Car_Price)
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)
carsDf = pd.merge(carPriceDf, carsHorsepowerDf, on="Company")
carsDf

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160